import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Nav from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* google fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        {/* FONT- Montserrat */}
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
        {/* FONT- Pacifico*/}
        <link
          href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body >
      <div id="smooth-wrapper">
        <div id="smooth-content"  >
        {children}
        <Footer />

        </div>

      </div>
      </body>
    </html>
  );
}
